sex 09 jan 2026 13:33:21 -04 Vilmar Catafesta (vcatafesta@gmail.com)

diff --git a/void-dialog-theme-selector b/void-dialog-theme-selector
--- a/void-dialog-theme-selector
+++ b/void-dialog-theme-selector
@@ -2,10 +2,10 @@
 # -*- coding: utf-8 -*-
 # shellcheck shell=bash disable=SC1091,SC2039,SC2166
 #
-#  void-dialog-theme-selector - Seletor de temas para o Dialog
+#  chili-dialog-theme-selector - Seletor de temas para o Dialog
 #  Created: 2025/02/03 - 00:54
 #  Altered: 2025/02/03 - 00:54
-#  Updated: sáb 08 fev 2025 20:04:45 -04
+#  Updated: dom 17 ago 2025 21:55:49 -04
 #
 #  Copyright (c) 2025-2025, Vilmar Catafesta <vcatafesta@gmail.com>
 #  All rights reserved.
@@ -32,7 +32,21 @@
 ##############################################################################
 #export LANGUAGE=pt_BR
 export TEXTDOMAINDIR=/usr/share/locale
-export TEXTDOMAIN=void-dialog-theme-selector
+export TEXTDOMAIN=chili-dialog-theme-selector
+
+#debug
+export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset} '
+#set -x
+#set -e
+shopt -s extglob
+
+#system
+declare APP="${0##*/}"
+declare _VERSION_='3.08.17.20250817'
+declare APPDESC="Seletor de temas para o Dialog"
+declare ccabec="ChiliLinux - $APP - v$_VERSION_ - $APPDESC"
+declare ctitle="Menu de Temas"
+declare DEPENDENCIES=(dialog setfont tput)
 
 # Definir a variável de controle para restaurar a formatação original
 reset=$(tput sgr0)
@@ -65,19 +79,38 @@ light_magenta=$(tput setaf 13)
 light_cyan=$(tput setaf 14)
 bright_white=$(tput setaf 15)
 
-#debug
-export PS4='${red}${0##*/}${green}[$FUNCNAME]${pink}[$LINENO]${reset}'
-#set -x
-#set -e
-shopt -s extglob
+# dialog colors
+REVERSE="\Zr"
+UNDERLINE="\Zu"
+BOLD="\Zb"
+RESET="\Zn"
+BLACK="\Z0"
+YELLOW="\Z3"
+WHITE="\Z7"
+BLUE="\Z4"
+CYAN="\Z6"
+RED="\Z1"
+GREEN="\Z2"
+MAGENTA="\Z5"
+sep='\xe2\x94\x82'
 
-#system
-declare APP="${0##*/}"
-declare _VERSION_="1.2.08-20250208"
-declare distro="$(uname -n)"
-declare DEPENDENCIES=(tput dialog)
-declare ccabec="$APP - Seletor de temas para o Dialog"
-declare ctitle="Menu de Temas"
+# flag dialog exit status codes
+: "${D_OK=0}"
+: "${D_CANCEL=1}"
+: "${D_HELP=2}"
+: "${D_EXTRA=3}"
+: "${D_ITEM_HELP=4}"
+: "${D_ESC=255}"
+
+cLB1=$(gettext "Use as teclas")
+cLB2=$(gettext "PARA CIMA")
+cLB3=$(gettext "e")
+cLB4=$(gettext "PARA BAIXO")
+cLB5=$(gettext "para navegar")
+cLB6=$(gettext "Use")
+cLB7=$(gettext "para alternar entre os botões")
+cLB8=$(gettext "para selecionar")
+cmsg_LABEL="$cLB1${BLUE} ↑ $cLB2$RESET $cLB3 ${BLUE}↓ $cLB4$RESET $cLB5\n$cLB6${BLUE} TAB${RESET} $cLB7${BLUE} ENTER${RESET} $cLB8"
 
 MostraErro() {
 	echo "erro: ${red}$1${reset} => comando: ${cyan}'$2'${reset} => result=${yellow}$3${reset}"
@@ -86,6 +119,142 @@ MostraErro() {
 
 # Declaração dos temas no array associativo
 declare -A themes=(
+	["Chili"]='
+aspect = 0
+separate_widget = ""
+tab_len = 0
+visit_items = ON
+use_shadow = ON
+use_colors = ON
+screen_color = (WHITE,BLACK,BLUE)
+shadow_color = (WHITE,BLACK,OFF)
+dialog_color = (BLACK,RED,OFF)
+title_color = (YELLOW,RED,ON)
+border_color = (RED,RED,ON)
+button_active_color = (YELLOW,BLACK,ON)
+button_inactive_color = dialog_color
+button_key_active_color = button_active_color
+button_key_inactive_color = (CYAN,RED,OFF)
+button_label_active_color = button_active_color
+button_label_inactive_color = (BLACK,RED,ON)
+inputbox_color = (BLUE,WHITE,OFF)
+inputbox_border_color = border_color
+searchbox_color = (YELLOW,WHITE,ON)
+searchbox_title_color = (WHITE,WHITE,ON)
+searchbox_border_color = (RED,WHITE,OFF)
+position_indicator_color = button_key_inactive_color
+menubox_color = dialog_color
+menubox_border_color = border_color
+item_color = dialog_color
+item_selected_color = screen_color
+tag_color = title_color
+tag_selected_color = screen_color
+tag_key_color = button_key_inactive_color
+tag_key_selected_color = (RED,BLUE,ON)
+check_color = dialog_color
+check_selected_color = (WHITE,RED,ON)
+uarrow_color = (RED,RED,ON)
+darrow_color = uarrow_color
+itemhelp_color = shadow_color
+form_active_text_color = inputbox_color
+form_text_color = (RED,BLUE,ON)
+form_item_readonly_color = (RED,WHITE,ON)
+gauge_color = (BLUE,WHITE,ON)
+border2_color = dialog_color
+inputbox_border2_color = border2_color
+searchbox_border2_color = border2_color
+menubox_border2_color = border2_color'
+
+	["Architect"]="
+screen_color = (white,black,off)
+dialog_color = (white,black,off)
+title_color = (cyan,black,on)
+border_color = dialog_color
+shadow_color = (black,black,on)
+button_inactive_color = dialog_color
+button_key_inactive_color = dialog_color
+button_label_inactive_color = dialog_color
+button_active_color = (white,cyan,on)
+button_key_active_color = button_active_color
+button_label_active_color = (black,cyan,on)
+tag_key_selected_color = (white,cyan,on)
+item_selected_color = tag_key_selected_color
+form_text_color = (BLUE,black,ON)
+form_item_readonly_color = (green,black,on)
+itemhelp_color = (white,cyan,off)
+inputbox_color = dialog_color
+inputbox_border_color = dialog_color
+searchbox_color = dialog_color
+searchbox_title_color = title_color
+searchbox_border_color = border_color
+position_indicator_color = title_color
+menubox_color = dialog_color
+menubox_border_color = border_color
+item_color = dialog_color
+tag_color = title_color
+tag_selected_color = button_label_active_color
+tag_key_color = button_key_inactive_color
+check_color = dialog_color
+check_selected_color = button_active_color
+uarrow_color = screen_color
+darrow_color = screen_color
+form_active_text_color = button_active_color
+gauge_color = title_color
+border2_color = dialog_color
+searchbox_border2_color = dialog_color
+menubox_border2_color = dialog_color
+separate_widget = ''
+tab_len = 0
+visit_items = off
+use_shadow = off
+use_colors = on"
+
+	["Slackware"]="
+aspect = 0
+separate_widget = ''
+tab_len = 0
+visit_items = OFF
+use_shadow = ON
+use_colors = ON
+screen_color = (WHITE,BLUE,OFF)
+shadow_color = (WHITE,BLACK,OFF)
+dialog_color = (BLACK,CYAN,OFF)
+title_color = (YELLOW,CYAN,ON)
+border_color = (CYAN,CYAN,ON)
+button_active_color = (WHITE,BLUE,ON)
+button_inactive_color = dialog_color
+button_key_active_color = button_active_color
+button_key_inactive_color = (RED,CYAN,OFF)
+button_label_active_color = button_active_color
+button_label_inactive_color = (BLACK,CYAN,ON)
+inputbox_color = (BLUE,WHITE,OFF)
+inputbox_border_color = border_color
+searchbox_color = (YELLOW,WHITE,ON)
+searchbox_title_color = (WHITE,WHITE,ON)
+searchbox_border_color = (RED,WHITE,OFF)
+position_indicator_color = button_key_inactive_color
+menubox_color = dialog_color
+menubox_border_color = border_color
+item_color = dialog_color
+item_selected_color = screen_color
+tag_color = title_color
+tag_selected_color = screen_color
+tag_key_color = button_key_inactive_color
+tag_key_selected_color = (RED,BLUE,ON)
+check_color = dialog_color
+check_selected_color = (WHITE,CYAN,ON)
+uarrow_color = (RED,CYAN,ON)
+darrow_color = uarrow_color
+itemhelp_color = shadow_color
+form_active_text_color = inputbox_color
+form_text_color = (CYAN,BLUE,ON)
+form_item_readonly_color = (CYAN,WHITE,ON)
+gauge_color = (BLUE,WHITE,ON)
+border2_color = dialog_color
+inputbox_border2_color = border2_color
+searchbox_border2_color = border2_color
+menubox_border2_color = border2_color"
+
 	["Azul e Branco"]="use_shadow = ON
 use_colors = ON
 screen_color = (BLUE,DEFAULT,OFF)
@@ -1627,50 +1796,6 @@ inputbox_border2_color = (WHITE,BLACK,OFF)
 searchbox_border2_color = (WHITE,BLACK,ON)
 menubox_border2_color = (WHITE,BLACK,ON)"
 
-	["Architect"]="
-screen_color = (white,black,off)
-dialog_color = (white,black,off)
-title_color = (cyan,black,on)
-border_color = dialog_color
-shadow_color = (black,black,on)
-button_inactive_color = dialog_color
-button_key_inactive_color = dialog_color
-button_label_inactive_color = dialog_color
-button_active_color = (white,cyan,on)
-button_key_active_color = button_active_color
-button_label_active_color = (black,cyan,on)
-tag_key_selected_color = (white,cyan,on)
-item_selected_color = tag_key_selected_color
-form_text_color = (BLUE,black,ON)
-form_item_readonly_color = (green,black,on)
-itemhelp_color = (white,cyan,off)
-inputbox_color = dialog_color
-inputbox_border_color = dialog_color
-searchbox_color = dialog_color
-searchbox_title_color = title_color
-searchbox_border_color = border_color
-position_indicator_color = title_color
-menubox_color = dialog_color
-menubox_border_color = border_color
-item_color = dialog_color
-tag_color = title_color
-tag_selected_color = button_label_active_color
-tag_key_color = button_key_inactive_color
-check_color = dialog_color
-check_selected_color = button_active_color
-uarrow_color = screen_color
-darrow_color = screen_color
-form_active_text_color = button_active_color
-gauge_color = title_color
-border2_color = dialog_color
-searchbox_border2_color = dialog_color
-menubox_border2_color = dialog_color
-separate_widget = ''
-tab_len = 0
-visit_items = off
-use_shadow = off
-use_colors = on"
-
 	["Jelly"]="
 use_shadow = OFF
 use_colors = ON
@@ -1901,16 +2026,24 @@ for key in "${!themes[@]}"; do
 	((count++))
 done
 
-theme_choice=$(dialog \
-              --colors \
-              --title "$ctitle" \
-              --backtitle "$ccabec" \
-              --menu "Escolha o tema desejado" 0 60 20 "${theme_list[@]}" 2>&1 >/dev/tty)
+while true; do
+	theme_choice=$(dialog \
+		--default-item "$theme_choice" \
+		--colors \
+		--title "$ctitle" \
+		--backtitle "$ccabec" \
+		--ok-label 'Selecionar' \
+		--cancel-label 'Sair' \
+		--menu "${cmsg_LABEL}\n\n${YELLOW}$(gettext "Escolha o tema desejado"):${RESET}" \
+		24 0 2 "${theme_list[@]}" \
+		2>&1 >/dev/tty)
 
-# Salvar o tema escolhido no arquivo .dialogrc
-if [ -n "$theme_choice" ]; then
-	echo "${themes[$theme_choice]}" >"$HOME/.dialogrc"
-	dialog --msgbox "Tema '$theme_choice' aplicado com sucesso!" 0 0
-else
-	dialog --msgbox "Nenhum tema escolhido!" 0 0
-fi
+	# Salvar o tema escolhido no arquivo .dialogrc
+	if [ -n "$theme_choice" ]; then
+		echo "${themes[$theme_choice]}" >"$HOME/.dialogrc"
+		dialog --msgbox "Tema '$theme_choice' aplicado com sucesso!" 0 0
+	else
+		#		dialog --msgbox "Nenhum tema escolhido!" 0 0
+		exit 0
+	fi
+done
